name: 'test-merge'
on:
  pull_request_target:
      branches: [ main ]

jobs:
  check-compare-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check compare branch
        run: |
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
          echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"
          echo "GITHUB_REF = $GITHUB_REF"
          echo ${{github.event.pull_request.head.sha}}
